services:
  - type: web
    name: avpprojecta
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: DATABASE_URL
        fromDatabase:
          name: avpprojecta-db
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync

databases:
  - name: avpprojecta-db
    plan: free
